### ISSUE TITLE
Projects Description

### ISSUE THREAD

**Issue by mraaroncruz** [rossconf/rossconf.io#4]
I think there should be a description of why we are showing the projects (RVM, Exercism) below the project headline.

**Comment by FloorD** [comment]
With <a href="http://exercism.io/" target="_blank">exercism</a> beginner programmers practice their coding skills while more experienced developers offer their mentorship. Thousands of thoughtful discussion on code decisions take place on exercism.io.

Ruby Version Manager (<a href="http://rvm.io/" target="_blank">RVM</a>) is a command-line tool which allows you to easily install, manage, and work with multiple ruby environments from interpreters to sets of gems.

or:
RVM was the first version manager for installing Ruby, to solve problems like switching Ruby versions or separating project gems. The first version was a success even if it took a few years for others to pick up on the idea. Today RVM is still leading in the area of installing and switching Ruby, but to keep it innovative @mpapis is working on a version 2.0.

<a href="https://joindiaspora.com/" target="_blank">diaspora_</a> is the community-run, distributed social network. The software is Rails based and was created in 2010 and is community governed since 2012. Today diaspora_ is one of the biggest alternatives to centralized social networks with an active and vibrant community.

**Comment by mraaroncruz** [comment]
Sorry, what I meant was, I don't know why those projects are shown there. Why are we listing three seemingly arbitrary open source projects? So something like

> Here are three projects that we are showcasing at ROSSConf. We think they are the bees' knees.

or

> We will hold workshops dealing with the following projects...

**Comment by FloorD** [comment]
Get it! Let me work on that. Please throw in a placeholder text for now :spaghetti:

**Comment by mraaroncruz** [comment]
great. thank you :joy_cat:
